---
project_name: git2consul
env:
  - CGO_ENABLED=0
builds:
  - ldflags:
    - "-X {{.Env.VERSION_PKG}}.Branch={{.Env.BRANCH}}"
    - "-X {{.Env.VERSION_PKG}}.BuildDate={{.Env.DATE}}"
    - "-X {{.Env.VERSION_PKG}}.GitSHA1={{.Env.COMMIT}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  skip: false
