---
language: go
matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x

before_install:
  - export GO111MODULE=on
  - go get golang.org/x/lint/golint

install:
  - # skip

script:
  - go mod vendor
  - test -z "$(gofmt -l . | grep -v ^vendor)"
  - golint $(go list ./... | grep -v /vendor/)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test $(go list ./... | grep -v /vendor/)
  - go build
