---
branches:
  only:
  - master
language: go
matrix:
  include:
    - go: 1.13.x

before_install:
  - GO111MODULE=off go get golang.org/x/lint/golint

install:
  - # skip

script:
  - make test-dirty
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
