[[constraint]]
name = "github.com/apex/log"
version = "~1.0.0"

[[constraint]]
name = "github.com/gorilla/mux"
version = "~1.6.2"

[[constraint]]
name = "github.com/hashicorp/consul"
version = "~1.1.0"

[[constraint]]
name = "gopkg.in/src-d/go-git.v4"
version = "^4.4.0"

[[constraint]]
name = "gopkg.in/yaml.v2"
version = "~2.2.1"

[prune]
go-tests = true
unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
